### ISSUE TITLE
Chocolatey package needs to be updated

### ISSUE THREAD

**Issue by gregnorz** [rgl/packer-plugin-windows-update#104]
Current version on Chocolatey is 0.11.0, which is 3 versions and 6 months out of date at the time of this issue.

Probably a separate issue to be logged, but if would be nice if the package used Chocolatey Automatic Updates to keep it current.

**Comment by rgl** [comment]
The package itself is deprecated. It's now managed by packer itself.

I will remove ASAP.

**Comment by rgl** [comment]
I've pushed https://community.chocolatey.org/packages/packer-provisioner-windows-update/0.12.0 which will deprecate the package as described at https://docs.chocolatey.org/en-us/community-repository/maintainers/deprecate-a-chocolatey-package#the-solution.

The package deprecation source will live at https://github.com/rgl/packer-plugin-windows-update/tree/deprecate-chocolatey-package.
