### ISSUE TITLE
'packer-windows-update-...' scheduled tasks left in the system

### ISSUE THREAD

**Issue by VladRassokhin** [rgl/packer-plugin-windows-update#106]
I've used windows-update version 0.14.0 provisioner on `amazon-ebs` builder with `Windows_Server-2019-English-Full-Base-*` as base AMI and in resulting AMI there's scheduled tasks with name prefix `packer-windows-update-`

**Comment by apoxa** [comment]
I'm also seeing that with version 0.14.1. There are 2 tasks present in the Task Scheduler after the build

1. `packer-windows-update-<UUID>`
2. `packer-windows-update-pending-reboot-<UUID>`

**Comment by rgl** [comment]
Implemented in #126.
