### ISSUE TITLE
[Question] name "windows-update" vs "packer-plugin-windows-update" 

### ISSUE THREAD

**Issue by smerle33** [rgl/packer-plugin-windows-update#109]
Hi,
Is there any reason not to use packer-plugin-windows-update as a path ?

`
windows-update = {
      version = "0.14.0"
      source = "github.com/rgl/windows-update"
    }
`

vs

`
windows-update = {
      version = "0.14.0"
      source = "github.com/rgl/packer-plugin-windows-update"
    }
`

as https://github.com/rgl/windows-update bring a 404 ....

Thanks for my understanding !
Stéphane

**Comment by rgl** [comment]
To be compatible with `packer init` it has to be named like that. Have a look at https://www.packer.io/docs/commands/init.
