### ISSUE TITLE
On Server 2012, scheduled task does not exit `101`, rather exits `2147942501` when reboot required

### ISSUE THREAD

**Issue by cailyoung** [rgl/packer-plugin-windows-update#130]
https://github.com/rgl/packer-plugin-windows-update/blob/6793f6375aa3b786be6ef36d571dc9d35f9f90de/update/provisioner.go#L279 appears to be the plumbing between the restart-required check (that uses a scheduled task under the hood) and the provisioner in order to decide what to do.

On many of our VM builds, this works fine, but on Server 2012 in particular this appears to get stuck, printing `Waiting for the Windows Modules Installer to exit...` to the console and logging `Retryable error: Windows update script exited with non-zero exit status: 2147942501` to the log.

It looks like some error/exit code translation is going on - https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499- suggests `101` _is_ this semaphore error that was referred to in #78 - perhaps running the task as `SYSTEM` causes some weird failure mode in Server 2012 specifically where the result code of the process in the scheduled task is mapped via the system error table?
<img width="860" alt="Screenshot 2023-08-23 at 4 26 49 pm" src="https://github.com/rgl/packer-plugin-windows-update/assets/3939499/52fe3cd9-cb4e-4a76-80e7-a2a2e48563a5">

**Comment by cailyoung** [comment]
I'm open to raising a PR for this but I'm not sure whether there's a preference to resolve this in the provisioner itself, or in the remote-end powershell scripts.

**Comment by cailyoung** [comment]
@rgl Sorry to ping you; I am happy to work on a PR for this but don't know if you have a preference for which layer the issue is addressed in. I could see adding another `case` and just accepting the 2012 return value, or I could see altering the remotely-executed PowerShell to handle Server 2012 (if possible!)

**Comment by cailyoung** [comment]
A reboot clears the problem (The exit code is returned _because_ a reboot is pending, it's just being misinterpreted during communication back to packer.

I'll work up a PR and test it out on our systems. I wish I was also no longer using Server 2012! :D

**Comment by matt-richardson** [comment]
@rgl - I've raised https://github.com/rgl/packer-plugin-windows-update/pull/134 to fix this issue.

Are you able to take a look and merge in if you're happ?
