### ISSUE TITLE
Failed getting the plugin

### ISSUE THREAD

**Issue by dreamland101** [rgl/packer-plugin-windows-update#140]
On packer init I get the same error every time:

Failed getting the "github.com/rgl/windows-update" plugin:
6 errors occurred:
        * ignoring invalid remote binary packer-plugin-windows-update_v0.14.0_x5.0_windows_amd64.zip: wrong system, expected windows_386
        * ignoring invalid remote binary packer-plugin-windows-update_v0.14.0_x5.0_darwin_arm64.zip: wrong system, expected windows_386
        * ignoring invalid remote binary packer-plugin-windows-update_v0.14.0_x5.0_linux_arm64.zip: wrong system, expected windows_386
        * ignoring invalid remote binary packer-plugin-windows-update_v0.14.0_x5.0_linux_amd64.zip: wrong system, expected windows_386
        * ignoring invalid remote binary packer-plugin-windows-update_v0.14.0_x5.0_darwin_amd64.zip: wrong system, expected windows_386
        * could not install any compatible version of plugin "github.com/rgl/windows-update"

Packer v 1.10.0 on Windows 11

**Comment by rgl** [comment]
You need a 64-bit packer binary and system.
