### ISSUE TITLE
Windows update fails with exit code 259 (some of the time)

### ISSUE THREAD

**Issue by NeilBostrom** [rgl/packer-plugin-windows-update#3]
I'm not sure if you will be able to help much with this but I'm running three builds in parallel and usually one of the builds fails with the below error:

> Windows update script exited with non-zero exit status: 259

In the log below the builder named "web" failed this time. Other times "files" and "tasks" builders might fail:

> 2017/07/14 10:56:12 ui:     web: EC2AMAZ-17MJEE2 restarted.
2017/07/14 10:56:12 packer-provisioner-windows-update.exe: 2017/07/14 10:56:12 [INFO] 28 bytes written for 'stdout'
2017/07/14 10:56:12 packer-provisioner-windows-update.exe: 2017/07/14 10:56:12 [INFO] 392 bytes written for 'stderr'
2017/07/14 10:56:12 packer-provisioner-windows-update.exe: 2017/07/14 10:56:12 [INFO] RPC client: Communicator ended with: 0
2017/07/14 10:56:12 ui:     web: #< CLIXML
2017/07/14 10:56:12 ui:     web: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
2017/07/14 10:56:12 packer-provisioner-windows-update.exe: 2017/07/14 10:56:12 Connected to machine
2017/07/14 10:56:12 ui: ==> web: Machine successfully restarted, moving on
2017/07/14 10:56:12 ui: ==> web: Running Windows update...
2017/07/14 10:56:12 packer.exe: 2017/07/14 10:56:12 [INFO] starting remote command: PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1
2017/07/14 10:56:15 ui:     web: Searching for Windows updates...
2017/07/14 10:59:23 packer.exe: 2017/07/14 10:59:23 [INFO] command 'PowerShell -ExecutionPolicy Bypass -OutputFormat Text -File C:/Windows/Temp/packer-windows-update-elevated.ps1' exited with code: 259
2017/07/14 10:59:23 packer.exe: 2017/07/14 10:59:23 [INFO] RPC endpoint: Communicator ended with: 259
2017/07/14 10:59:23 [INFO] 34 bytes written for 'stdout'
2017/07/14 10:59:23 [INFO] RPC client: Communicator ended with: 259
2017/07/14 10:59:23 [INFO] 0 bytes written for 'stderr'
2017/07/14 10:59:23 [INFO] RPC endpoint: Communicator ended with: 259
2017/07/14 10:59:23 packer-provisioner-windows-update.exe: 2017/07/14 10:59:23 [INFO] 34 bytes written for 'stdout'
2017/07/14 10:59:23 packer-provisioner-windows-update.exe: 2017/07/14 10:59:23 [INFO] 0 bytes written for 'stderr'
2017/07/14 10:59:23 packer-provisioner-windows-update.exe: 2017/07/14 10:59:23 [INFO] RPC client: Communicator ended with: 259
2017/07/14 10:59:23 ui: ==> web: Terminating the source AWS instance...
2017/07/14 10:59:23 packer.exe: 2017/07/14 10:59:23 Waiting for state to become: terminated
2017/07/14 10:59:23 packer.exe: 2017/07/14 10:59:23 Using 2s as polling delay (change with AWS_POLL_DELAY_SECONDS)
2017/07/14 10:59:23 packer.exe: 2017/07/14 10:59:23 Allowing 300s to complete (change with AWS_TIMEOUT_SECONDS)
2017/07/14 10:59:28 ui:     tasks: Installing Windows updates...
2017/07/14 11:01:41 ui:     files: Pending Reboot detected. Waiting for the Windows Modules Installer to exit...
2017/07/14 11:01:45 ui: ==> web: Cleaning up any extra volumes...
2017/07/14 11:01:45 ui: ==> web: No volumes to clean up, skipping
2017/07/14 11:01:45 ui: ==> web: Deleting temporary keypair...

I've had problems in general with Packer with WinRM failing at times. It seems to randomly fail sometimes doing it. Not sure if that is related or not.

I know this is a very wooly bug report but it was mostly down to if you knew any reason why I would get a exit code of 259.

**Comment by tvories** [comment]
What does your packer config look like for calling the windows-update provisioner?

**Comment by rgl** [comment]
Also, did any of the builds succeeded?

**Comment by NeilBostrom** [comment]
@tvories My packer config looks like:

>{
  "builders": [
    {
      "name": "tasks",
      "type": "amazon-ebs",
      "communicator": "winrm",
      "user_data_file": "./ec2-userdata.ps1",
      "ami_name": "base-tasks",
      "tags": {
        "Name": "base-tasks-{{isotime \"2006-01-02\"}}"
      },
      "region": "eu-west-1",
      "instance_type": "m4.large",
      "iam_instance_profile": "dev-build-role",
      "vpc_id": "vpc-4afbea2e",
      "subnet_id": "subnet-43213827",
      "ami_users": "150445443113",
      "force_deregister": true,
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "Windows_Server-2016-English-Full-Base-*",
          "root-device-type": "ebs"
        },
        "owners": [ "801119661308" ],
        "most_recent": true
      },
      "run_tags": {
        "Name": "builder-tasks-{{isotime \"2006-01-02\"}}"
      },
      "security_group_id": "sg-b2498acb",
      "winrm_username": "Administrator",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "disable_stop_instance": true
    },
    {
      "name": "web",
      "type": "amazon-ebs",
      "communicator": "winrm",
      "user_data_file": "./ec2-userdata.ps1",
      "ami_name": "base-web",
      "tags": {
        "Name": "base-web-{{isotime \"2006-01-02\"}}"
      },
      "region": "eu-west-1",
      "instance_type": "m4.large",
      "iam_instance_profile": "dev-build-role",
      "vpc_id": "vpc-4afbea2e",
      "subnet_id": "subnet-43213827",
      "ami_users": "150445443113",
      "force_deregister": true,
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "Windows_Server-2016-English-Full-Base-*",
          "root-device-type": "ebs"
        },
        "owners": [ "801119661308" ],
        "most_recent": true
      },
      "run_tags": {
        "Name": "builder-web-{{isotime \"2006-01-02\"}}"
      },
      "security_group_id": "sg-b2498acb",
      "winrm_username": "Administrator",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "disable_stop_instance": true
    },
    {
      "name": "files",
      "type": "amazon-ebs",
      "communicator": "winrm",
      "user_data_file": "./ec2-userdata.ps1",
      "ami_name": "base-files",
      "tags": {
        "Name": "base-files-{{isotime \"2006-01-02\"}}"
      },
      "region": "eu-west-1",
      "instance_type": "m4.large",
      "iam_instance_profile": "dev-build-role",
      "vpc_id": "vpc-4afbea2e",
      "subnet_id": "subnet-43213827",
      "ami_users": "150445443113",
      "force_deregister": true,
      "source_ami_filter": {
        "filters": {
          "virtualization-type": "hvm",
          "name": "Windows_Server-2016-English-Full-Base-*",
          "root-device-type": "ebs"
        },
        "owners": [ "801119661308" ],
        "most_recent": true
      },
      "run_tags": {
        "Name": "builder-files-{{isotime \"2006-01-02\"}}"
      },
      "security_group_id": "sg-b2498acb",
      "winrm_username": "Administrator",
      "winrm_use_ssl": true,
      "winrm_insecure": true,
      "disable_stop_instance": true
    }
  ],
  "provisioners": [
    {
      "type": "powershell",
      "inline": [ "c:\\bootstrap\\bootstrap.ps1" ]
    },
    {
      "type": "windows-restart"
    },
    {
      "type": "windows-update"
    },
    {
      "type": "windows-restart"
    },
    {
      "type": "powershell",
      "inline": [ "c:\\bootstrap\\ngen.ps1" ]
    },
    {
      "type": "windows-restart"
    },
    {
      "type": "powershell",
      "inline": [ "c:\\bootstrap\\sysprep.ps1" ]
    }
  ]
}

**Comment by NeilBostrom** [comment]
@rgl Some of the builds are going through. It seems an intermittent issue. I've suffered similar problems with WinRM in general with packer.

**Comment by joshoohaah** [comment]
👍  to this issue.  I have been getting error `259` (ie reboot scheduled)  for all my builds..not intermittent.   I wonder if adding/taking the attribute `valid_exit_codes` functionality from the `powershell` provisioner would help this.  or have the plugin itself recognize `0` and `259` as acceptable exit codes.

**Comment by ttdgcp** [comment]
@rgl I experienced this today as well. Is there any work around for the 259 exit code?

**Comment by rgl** [comment]
I cannot reproduce this issue, so I do not really known or have a clue about what is going on. Is it reasonable to treat 259 as 101 (reboot pending?). Can you change the code for that and try it yourself?

BTW, are you using v0.5.1?

**Comment by ttdgcp** [comment]
@rgl Thanks for the quick response. I re-ran the exact same setup and it worked 😢 
I think it would be reasonable to treat 259 as 101 (reboot pending), as the error seems to indicate that.
I did download the latest version before running, but will double check I am on v0.5.1.

Also wanted to say thanks for this great provisioner-- much better than a PowerShell script!

**Comment by Marcus-James-Adams** [comment]
Before and after I call windows-update I cal the windows-restart provisioner as we have some software that is very "restart status" sensitive, having the before one also seems to cure any funnies widows and rm throws during this provisioner as well.

**Comment by Marcus-James-Adams** [comment]
and seconding the better than PowerShell script comment - using the "known" scripts to update was driving me mad onbuilds.

**Comment by rgl** [comment]
Please try with the new 0.6.0 and packer 1.2.5 (restart is broken after that release, so stick with 1.2.5 for now), winrm, and use the provision step without any options, i.e.:

```json
{
    "provisioners": [
        {
            "type": "windows-update"
        }
    ]
}
```

It should now install all recommended updates alike the windows update ui.

**Comment by agowa338** [comment]
Still occurs with latest versions, but only very rarely.

**Comment by lcizzle** [comment]
Hello,

I'm pretty sure the issue here is related VMWare Tools Installation and the timing of the install. The installation of VMWare Tools completes during the search and installation of Windows Updates. The new VMWare Tools has a popup on completion asking you if you want to reboot yes or no. If you don't reply it reboots automatically in the middle of Windows Updates causing the 259 error.

**Comment by tvories** [comment]
@lcizzle I'm not seeing in the config where they are installing VMWare Tools.  I actually ran into that issue as well and had to write an installer wrapper to fix the issue, but I'm not seeing that being installed in the above posts.

**Comment by lcizzle** [comment]
@tvories You are correct, looks like I jumped the gun! My bad.

**Comment by mananpatel** [comment]
@rgl I still have a build failing with exit code 259. In may case though, plug-in find 4 updates and manage to install them. Reboot the server. All fine till this point. But then plug-in start to search for for updates again. However, on windows screen I can see its still configuring updates and before it finished configuring plug-in is giving up and the build exited with 259 error and no artifacts are created.
I am using packer 1.2.5 and plug-in 0.6.1 (tried 0.6.0 with same result). I am using provision steps without any options as you had mentioned above.

Any idea? Thanks..

**Comment by rgl** [comment]
Please try [v0.14.0](https://github.com/rgl/packer-plugin-windows-update/releases/tag/v0.14.0) and let us known how it goes.

**Comment by NeilBostrom** [comment]
I believe this issue is fixed. I've not seen this issue in a while.
