### ISSUE TITLE
Unable to retrieve KB4505056

### ISSUE THREAD

**Issue by napalm684** [rgl/packer-plugin-windows-update#38]
Version v0.7.1
Packer Version v1.3.5 (1.4.x seems to have issues with Chocolatey)

The plugin despite many search attempts: "*Cumulative*", "*KB4505056*", "*Cumulative Update for Windows Server 2019 (1809)*", etc. does not select the following result Windows Update on the server wants to apply:

https://support.microsoft.com/en-us/help/4505056/windows-10-update-kb4505056

It does however find the one other update KB2267602 without issue.

**Comment by rgl** [comment]
Try like https://github.com/rgl/windows-2016-vagrant/commit/859f9edf5014e4fe1b8058ccdf8efcdfc3f26da4

**Comment by napalm684** [comment]
That’s what I have tried it doesn’t find the result with any of the search queries I mentioned above.

**Comment by rgl** [comment]
Whats the exact template snippets that are you using and the logs?

It seems packer has changed the way it looks for its plugins. You have to manually put it in your `%USERPROFILE%\packer.d\plugins` directory.

**Comment by napalm684** [comment]
This is the provisioner I tried the multiple search terms mentioned above in:

```
      {
        "type": "windows-update",
        "filters": [
          "include:$_.Title -like '*Cumulative*'"
        ]
      },
```

Log:

```
==> amazon-ebs: Uploading the Windows update elevated script...
==> amazon-ebs: Uploading the Windows update check for reboot required elevated script...
==> amazon-ebs: Uploading the Windows update script...
==> amazon-ebs: Running Windows update...
    amazon-ebs: Searching for Windows updates...
    amazon-ebs: Skipped (filter) Windows update (2019-05-21; 202.8 MB): Definition Update for Windows Defender Antivirus - KB2267602 (Definition 1.293.2058.0)
    amazon-ebs: No Windows updates found
```

As you can tell, it finds 1 of the 2 updates available, not the Cumulative update.

**Comment by rgl** [comment]
I'm have no idea of what is happening. If you manually run windows updates inside the machine are all the updates found?

You can also try to manually run https://github.com/rgl/packer-provisioner-windows-update/blob/master/update/windows-update.ps1 to see if it finds something different.

**Comment by rgl** [comment]
Oh run it as `PowerShell windows-update.ps1 -SearchCriteria 'IsInstalled=0'`

**Comment by napalm684** [comment]
@rgl Yes the server finds both

![image](https://user-images.githubusercontent.com/8197405/58120966-50c6cd80-7bd4-11e9-95bf-de7399e7a720.png)

Just to be clear you are advocating running the powershell script manually instead of using the windows-update provisioner?

**Comment by rgl** [comment]
Only for troubleshooting your particular issue, since its normally faster to manually execute the script than start a new VM from scratch.

BTW, I test this plugin with windows 2016/10/2019 base isos (e.g. at https://github.com/rgl/windows-2016-vagrant/blob/master/windows-2019.json) on on-prem VirtualBox, kvm and vSphere hypervisors and I never seen your issue before.

**Comment by napalm684** [comment]
Maybe EC2 specific?  I am baking an AMI.

**Comment by rgl** [comment]
Could be... I don't known.

What was the result of manually running `PowerShell windows-update.ps1 -SearchCriteria 'IsInstalled=0'`?

**Comment by napalm684** [comment]
Haven't forgotten about this hope to try this week.

**Comment by napalm684** [comment]
Oops it appears I did forget about this, apologies I have items this sprint related to using this plugin.
