### ISSUE TITLE
Windows update script exited with non-zero exit status: 2147942501

### ISSUE THREAD

**Issue by tempora-mutantur** [rgl/packer-plugin-windows-update#78]
Hi.

I'm updating my Windows Server 2012

And here is my log:

17:19:33  ==> vsphere-clone: Uploading the Windows update elevated script...
17:19:34  ==> vsphere-clone: Uploading the Windows update check for reboot required elevated script...
17:19:35  ==> vsphere-clone: Uploading the Windows update script...
17:19:35  ==> vsphere-clone: Running Windows update...
17:19:42      vsphere-clone: Searching for Windows updates...
17:20:38      vsphere-clone: Waiting for operation to complete (system performance: 81% cpu; 44% memory)...
17:21:46      vsphere-clone: Waiting for operation to complete (system performance: 22% cpu; 61% memory)...
17:22:24      vsphere-clone: Found Windows update (2020-01-14; 74.93 MB): Windows Server 2012 x64 ç”¨ Microsoft .NET Framework 4.8 (KB4486081)
17:22:24      vsphere-clone: Found Windows update (2020-02-11; 53.3 MB): Windows Server 2012 (x64 ãƒ™ãƒ¼ã‚¹ ã‚·ã‚¹ãƒ†ãƒ ) ã�® Internet Explorer 11
17:22:24      vsphere-clone: Found Windows update (2020-07-14; 9.74 MB): 2020-07x64 ãƒ™ãƒ¼ã‚¹ ã‚·ã‚¹ãƒ†ãƒ ç”¨ Windows Server 2012 ã‚µãƒ¼ãƒ“ã‚¹ ã‚¹ã‚¿ãƒƒã‚¯æ›´æ–°ãƒ—ãƒ­ã‚°ãƒ©ãƒ  (KB4566426)
17:22:24      vsphere-clone: Found Windows update (2020-08-11; 70.46 MB): 2020-08 Windows Server 2012 (x64 ç‰ˆ) ç”¨ .NET Framework 3.5ã€�4.5.2ã€�4.6ã€�4.6.1ã€�4.6.2ã€�4.7ã€�4.7.1ã€�4.7.2ã€�4.8 ã�®ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ã�Šã‚ˆã�³å“�è³ªãƒ­ãƒ¼ãƒ«ã‚¢ãƒƒãƒ— (KB4570507)
17:22:24      vsphere-clone: Found Windows update (2020-08-11; 375.13 MB): 2020-08 x64 ãƒ™ãƒ¼ã‚¹ ã‚·ã‚¹ãƒ†ãƒ ç”¨ Windows Server 2012 å�‘ã�‘ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£ ãƒžãƒ³ã‚¹ãƒªãƒ¼å“�è³ªãƒ­ãƒ¼ãƒ«ã‚¢ãƒƒãƒ— (KB4571736)
17:22:24      vsphere-clone: Downloading Windows updates (5 updates; 583.56 MB)...
17:22:43      vsphere-clone: Waiting for operation to complete (system performance: 39% cpu; 19% memory)...
17:23:50      vsphere-clone: Waiting for operation to complete (system performance: 77% cpu; 27% memory)...
17:24:46      vsphere-clone: Waiting for operation to complete (system performance: 47% cpu; 31% memory)...
17:24:48      vsphere-clone: Installing Windows updates...
17:25:44      vsphere-clone: Waiting for operation to complete (system performance: 84% cpu; 30% memory)...
17:26:52      vsphere-clone: Waiting for operation to complete (system performance: 41% cpu; 30% memory)...
17:27:48      vsphere-clone: Waiting for operation to complete (system performance: 1% cpu; 30% memory)...
17:28:56      vsphere-clone: Waiting for operation to complete (system performance: 37% cpu; 34% memory)...
17:29:52      vsphere-clone: Waiting for operation to complete (system performance: 19% cpu; 29% memory)...
17:30:39      vsphere-clone: Waiting for the Windows Modules Installer to exit...
17:30:51      vsphere-clone: Waiting for operation to complete (system performance: 0% cpu; 32% memory)...
17:31:58      vsphere-clone: Waiting for operation to complete (system performance: 16% cpu; 33% memory)...
17:32:55      vsphere-clone: Waiting for operation to complete (system performance: 0% cpu; 32% memory)...
17:33:33  ==> vsphere-clone: Provisioning step had errors: Running the cleanup provisioner, if present...
17:33:33  ==> vsphere-clone: Power off VM...
17:33:33  ==> vsphere-clone: Destroying VM...
17:33:33  **Build 'vsphere-clone' errored: Windows update script exited with non-zero exit status: 2147942501**

As I understand, our scheduled task that runs updates returned this exit code. Converted to hex, the error code would be 0x8007 0065 - "The exclusive semaphore is owned by another process."

I'll continue looking into the problem, but with no success for now.

**Comment by rgl** [comment]
Please try [v0.14.0](https://github.com/rgl/packer-plugin-windows-update/releases/tag/v0.14.0) and let us known how it goes.

**Comment by tempora-mutantur** [comment]
Found out that in that cases such updates can't been installed even manually.
