### ISSUE TITLE
Packer Init for Packer 1.7.#

### ISSUE THREAD

**Issue by animatco** [rgl/packer-plugin-windows-update#89]
First off, thank you for a great Provisioner. Does the repo support the new Packer Init functionality?

Steve

**Comment by vishalbasra** [comment]
I'm seeing this on  https://www.packer.io/docs/plugins
```
If the name starts with packer-plugin-, then it is a multi-component plugin. If the name starts with a prefix that actually says the component type (e.g. packer-provisioner- or packer-builder), then it is a single-component plugin.
Note: Only multi-component plugin binaries -- that is plugins named packer-plugin-*, like the packer-plugin-amazon -- are expected to work with Packer init. The legacy builder, post-processor and provisioner plugin types will keep on being detected but Packer cannot install them automatically. If a plugin you use has not been upgraded to use the multi-component plugin architecture, contact your maintainer to request an upgrade.
```
and while https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.11.0 states that 1.7.0 is required init won't work, can the name be changed in this repo?

**Comment by vishalbasra** [comment]
> I'm seeing this on https://www.packer.io/docs/plugins
> 
> ```
> If the name starts with packer-plugin-, then it is a multi-component plugin. If the name starts with a prefix that actually says the component type (e.g. packer-provisioner- or packer-builder), then it is a single-component plugin.
> Note: Only multi-component plugin binaries -- that is plugins named packer-plugin-*, like the packer-plugin-amazon -- are expected to work with Packer init. The legacy builder, post-processor and provisioner plugin types will keep on being detected but Packer cannot install them automatically. If a plugin you use has not been upgraded to use the multi-component plugin architecture, contact your maintainer to request an upgrade.
> ```
> 
> and while https://github.com/rgl/packer-provisioner-windows-update/releases/tag/v0.11.0 states that 1.7.0 is required init won't work, can the name be changed in this repo?

I reckon changing the binary name should suffice. Requested a different plugin owner to do the same and it worked ( see this https://github.com/martinbaillie/packer-plugin-ami-copy/issues/13  )

**Comment by rgl** [comment]
Done at https://github.com/rgl/packer-plugin-windows-update/releases/tag/v0.12.0.

I'm also start using this at https://github.com/rgl/windows-vagrant/commit/8bf819b5118eba806430443ce630a71f21dafacf.
