### ISSUE TITLE
windows-update skipping updates. 

### ISSUE THREAD

**Issue by Kristjanf-droid** [rgl/packer-plugin-windows-update#96]
Nomad version :1.7.3
    windows-update = {
      version = "0.12.0"
      source  = "github.com/rgl/windows-update"
    }
 when running the windows-update provisioner with the current config it skips the updates. 
   provisioner "windows-update" {
    search_criteria = "IsInstalled=0"
    filters = [
      "exclude=$_.Title -like '*Preview*'",
      "include=$true"
    ]
  }
  
  Deployment log:
   vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2020-10-13; 21.17 MB): 2020-10 Security Update for Adobe Flash Player for Windows Server 2019 for x64-based Systems (KB4580325)
    vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2021-01-12; 0.05 MB): Security Update for Windows Server 2019 for x64-based Systems (KB4535680)
    vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2021-02-16; 0.02 MB): Update for Removal of Adobe Flash Player for Windows Server 2019 for x64-based systems (KB4577586)
    vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2021-06-08; 33.48 MB): Windows Malicious Software Removal Tool x64 - v5.90 (KB890830)
    vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2021-06-15; 75.95 MB): 2021-06 Cumulative Update Preview for .NET Framework 3.5, 4.7.2 and 4.8 for Windows Server 2019 for x64 (KB5003857)
    vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2021-06-30; 97.9 MB): Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.343.118.0)
    vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2021-06-14; 0.07 MB): VMware, Inc. - Net - 1.9.2.0
    vsphere-iso.windows-server-iis: Skipped (filter) Windows update (2021-06-08; 16049.01 MB): 2021-06 Cumulative Update for Windows Server 2

**Comment by rgl** [comment]
You have a typo in the filter lines. You must use a colon symbol:

```
ACTION:EXPRESSION
```
