### ISSUE TITLE
Issue with VSTS Azure DevOps Pipeline and Packer 1.7.2

### ISSUE THREAD

**Issue by zkhcohen** [rgl/packer-plugin-windows-update#97]
Hey.

I receive the following issue when attempting to use this Packer Provisioner with Packer 1.7.2 installed to a VSTS Azure Devops Pipeline via Chocolatey...

Initial spin-up of validation stage where it discovers the internal plugin:

```C:\ProgramData\Chocolatey\bin\packer.exe validate -var-file=D:\a\_temp\de57fm6mvtb.json -var-file=D:\a\_temp\hc30d1fdha5.json D:\a\1\s\Packer\custom-2016-fixed.json
2021/07/02 00:25:57 [INFO] Packer version: 1.7.2 [go1.16.3 windows amd64]
2021/07/02 00:25:57 [TRACE] discovering plugins in C:\ProgramData\Chocolatey\lib\packer\tools
2021/07/02 00:25:57 [TRACE] discovering plugins in C:\Users\VssAdministrator\AppData\Roaming\packer.d\plugins
2021/07/02 00:25:57 [DEBUG] Discovered plugin: windows-update = C:\Users\VssAdministrator\AppData\Roaming\packer.d\plugins\packer-provisioner-windows-update.exe
2021/07/02 00:25:57 using external provisioners [windows-update]
2021/07/02 00:25:57 [TRACE] discovering plugins in .
2021/07/02 00:25:57 [INFO] PACKER_CONFIG env var not set; checking the default config file path
2021/07/02 00:25:57 [INFO] PACKER_CONFIG env var set; attempting to open config file: C:\Users\VssAdministrator\AppData\Roaming\packer.config
2021/07/02 00:25:57 [WARN] Config file doesn't exist: C:\Users\VssAdministrator\AppData\Roaming\packer.config
2021/07/02 00:25:57 [INFO] Setting cache directory: D:\a\1\s\packer_cache
```

The specific failure point:

```2021/07/02 00:25:58 [TRACE] Starting external plugin C:\Users\VssAdministrator\AppData\Roaming\packer.d\plugins\packer-provisioner-windows-update.exe 
2021/07/02 00:25:58 Starting plugin: C:\Users\VssAdministrator\AppData\Roaming\packer.d\plugins\packer-provisioner-windows-update.exe []string{"C:\\Users\\VssAdministrator\\AppData\\Roaming\\packer.d\\plugins\\packer-provisioner-windows-update.exe"}
2021/07/02 00:25:58 Waiting for RPC address for: C:\Users\VssAdministrator\AppData\Roaming\packer.d\plugins\packer-provisioner-windows-update.exe
2021/07/02 00:25:58 packer-provisioner-windows-update.exe plugin: 2021/07/02 00:25:58 **Starting packer-plugin-windows-update (version 0.12.0; commit ed5cb10b6e5857c4d85747ca4aa43f07ef30c727; date 2021-04-18T21:07:09Z)**
2021/07/02 00:25:58 packer-provisioner-windows-update.exe plugin: 2021/07/02 00:25:58 **Failed to start: needs at least one argument**
2021/07/02 00:25:58 C:\Users\VssAdministrator\AppData\Roaming\packer.d\plugins\packer-provisioner-windows-update.exe: plugin process exited

error initializing provisioner 'windows-update': plugin exited before we could
connect
```

It's worth noting that I'm simply copying the plugin .exe file to the path: C:\Users\VssAdministrator\AppData\Roaming\packer.d\plugins

Copying it next to the packer.exe (C:\ProgramData\Chocolatey\bin\packer.exe) results in a failure to detect the plugin, despite:
```2021/07/02 00:25:57 [TRACE] discovering plugins in .```

Any ideas what the issue could be?

**Comment by rgl** [comment]
Never tried it like that. You could try running in your machine and/or install it with packer init instead.

**Comment by zkhcohen** [comment]
> Never tried it like that. You could try running in your machine and/or install it with packer init instead.

Switching away from the built-in Packer tool and using Packer init resolved the issue!

Thanks.

**Comment by rgl** [comment]
What is the `riezebosch version`?

**Comment by zkhcohen** [comment]
> What is the `riezebosch version`?

https://marketplace.visualstudio.com/items?itemName=riezebosch.Packer

**Comment by rgl** [comment]
Interesting. I never really used Azure DevOps. That seems to be equivalent to the [packer github actions](https://github.com/marketplace/actions/packer-github-actions).

Is there any particular reason for using Azure DevOps over GitHub Actions?

To create the Virtual Machines are you using https://www.packer.io/docs/builders/azure/arm?

**Comment by zkhcohen** [comment]
> Is there any particular reason for using Azure DevOps over GitHub Actions?

We use Azure DevOps to integrate with our hybrid cloud environment, not GitHub.
On-premise, I'm hosting this in Docker to integrate with VMWare clusters.

> To create the Virtual Machines are you using https://www.packer.io/docs/builders/azure/arm?

ARM is utilized for the provisioning of the temporary VMs during the image build process, but the final VMs created out of the golden image are deployed using Terraform.

**Comment by rgl** [comment]
> On-premise, I'm hosting this in Docker to integrate with VMWare clusters.

What do you mean by "hosting in docker"? Can you explain what is the relation between docker, golden image, and a VMware VM? And what is the flow between those? :-)

**Comment by zkhcohen** [comment]
> What do you mean by "hosting in docker"? Can you explain what is the relation between docker, golden image, and a VMware VM? And what is the flow between those? :-)

Packer is containerized in Docker. Running the Packer build generates a 'golden image' of Windows Server which is deployed to a VMware ESXi cluster. 

Check out the builders here: https://www.packer.io/docs/builders/vmware

**Comment by rgl** [comment]
I see, I now understand what you mean by `hosted in docker`. What is being hosted is `packer` and you build it from there.
