### ISSUE TITLE
Add Mac M1 support

### ISSUE THREAD

**Issue by RomLecat** [rgl/packer-plugin-windows-update#99]
Hello,

Could you add support for new Apple Silicon chips (darwin arm64) to support the new M1 Macs ?

Thanks

**Comment by rgl** [comment]
I don't have access to that hardware to test.

You might be able to test and add it yourself by modifying https://github.com/rgl/packer-plugin-windows-update/blob/master/.goreleaser.yml and open a PR :-)

**Comment by RomLecat** [comment]
Just built it and tested it, it works fine. Submitted #100 :)
